package com.example.astronomy

/**
 * Astronomical catalog of well-documented Messier, NGC, and double-star targets.
 * Modular catalog structure that can be easily expanded.
 */
object DeepSkyCatalog {

    val objects: List<DeepSkyObject> = listOf(
        DeepSkyObject(
            id = "M42",
            messierNgc = "M42 / NGC 1976",
            commonName = "Nebulosa de Órion",
            constellation = "Órion",
            type = DeepSkyType.NEBULA,
            rightAscensionHours = 5.588,
            declinationDeg = -5.39,
            apparentMagnitude = 4.0,
            angularSizeArcmin = 65.0,
            surfaceBrightness = 11.5,
            description = "Uma das nebulosas mais brilhantes do céu, com berçário estelar ativo e o famoso sistema do Trapézio no centro.",
            bestFilter = "UHC ou OIII"
        ),
        DeepSkyObject(
            id = "M45",
            messierNgc = "M45",
            commonName = "Plêiades (As Sete Irmãs)",
            constellation = "Touro",
            type = DeepSkyType.OPEN_CLUSTER,
            rightAscensionHours = 3.783,
            declinationDeg = 24.11,
            apparentMagnitude = 1.6,
            angularSizeArcmin = 110.0,
            surfaceBrightness = 12.0,
            description = "Espetacular aglomerado aberto visível a olho nu. Excelente em oculares de campo amplo com baixa amplificação.",
            bestFilter = "Nenhum (Campo amplo)"
        ),
        DeepSkyObject(
            id = "M31",
            messierNgc = "M31 / NGC 224",
            commonName = "Galáxia de Andrômeda",
            constellation = "Andrômeda",
            type = DeepSkyType.GALAXY,
            rightAscensionHours = 0.712,
            declinationDeg = 41.27,
            apparentMagnitude = 3.4,
            angularSizeArcmin = 190.0,
            surfaceBrightness = 13.5,
            description = "A galáxia espiral gigante mais próxima da Via Láctea. Em céus escuros revela núcleo brilhante e galáxias satélites M32 e M110.",
            bestFilter = "Nenhum / Filtro de poluição"
        ),
        DeepSkyObject(
            id = "M27",
            messierNgc = "M27 / NGC 6853",
            commonName = "Nebulosa do Haltere (Dumbbell)",
            constellation = "Vulpécula",
            type = DeepSkyType.PLANETARY_NEBULA,
            rightAscensionHours = 19.993,
            declinationDeg = 22.72,
            apparentMagnitude = 7.5,
            angularSizeArcmin = 8.0,
            surfaceBrightness = 11.2,
            description = "A primeira nebulosa planetária descoberta na história, com formato característico de haltere de halteres.",
            bestFilter = "OIII ou UHC"
        ),
        DeepSkyObject(
            id = "M57",
            messierNgc = "M57 / NGC 6720",
            commonName = "Nebulosa do Anel",
            constellation = "Lira",
            type = DeepSkyType.PLANETARY_NEBULA,
            rightAscensionHours = 18.893,
            declinationDeg = 33.03,
            apparentMagnitude = 8.8,
            angularSizeArcmin = 1.4,
            surfaceBrightness = 9.8,
            description = "Um anel de gás luminescente expandido por uma estrela moribunda no centro. Responde muito bem a aumentos médios a altos.",
            bestFilter = "OIII"
        ),
        DeepSkyObject(
            id = "M13",
            messierNgc = "M13 / NGC 6205",
            commonName = "Aglomerado de Hércules",
            constellation = "Hércules",
            type = DeepSkyType.GLOBULAR_CLUSTER,
            rightAscensionHours = 16.695,
            declinationDeg = 36.46,
            apparentMagnitude = 5.8,
            angularSizeArcmin = 20.0,
            surfaceBrightness = 12.0,
            description = "O mais famoso aglomerado globular do hemisfério norte, contendo centenas de milhares de estrelas concentradas.",
            bestFilter = "Nenhum"
        ),
        DeepSkyObject(
            id = "M81",
            messierNgc = "M81 / NGC 3031",
            commonName = "Galáxia de Bode",
            constellation = "Ursa Maior",
            type = DeepSkyType.GALAXY,
            rightAscensionHours = 9.927,
            declinationDeg = 69.07,
            apparentMagnitude = 6.9,
            angularSizeArcmin = 27.0,
            surfaceBrightness = 13.0,
            description = "Galáxia espiral brilhante de núcleo bem definido. Frequentemente observada no mesmo campo com a galáxia M82.",
            bestFilter = "Nenhum"
        ),
        DeepSkyObject(
            id = "M82",
            messierNgc = "M82 / NGC 3034",
            commonName = "Galáxia do Charuto",
            constellation = "Ursa Maior",
            type = DeepSkyType.GALAXY,
            rightAscensionHours = 9.931,
            declinationDeg = 69.68,
            apparentMagnitude = 8.4,
            angularSizeArcmin = 11.0,
            surfaceBrightness = 12.5,
            description = "Galáxia 'starburst' com explosão intensa de formação estelar causada pela interação gravitacional com M81.",
            bestFilter = "Nenhum"
        ),
        DeepSkyObject(
            id = "M8",
            messierNgc = "M8 / NGC 6523",
            commonName = "Nebulosa da Lagoa",
            constellation = "Sagitário",
            type = DeepSkyType.NEBULA,
            rightAscensionHours = 18.063,
            declinationDeg = -24.38,
            apparentMagnitude = 6.0,
            angularSizeArcmin = 90.0,
            surfaceBrightness = 12.5,
            description = "Gigantesca nuvem de gás e poeira no centro da Via Láctea, contendo o aglomerado aberto NGC 6530 em seu interior.",
            bestFilter = "UHC ou OIII"
        ),
        DeepSkyObject(
            id = "M20",
            messierNgc = "M20 / NGC 6514",
            commonName = "Nebulosa Trífida",
            constellation = "Sagitário",
            type = DeepSkyType.NEBULA,
            rightAscensionHours = 18.043,
            declinationDeg = -23.03,
            apparentMagnitude = 6.3,
            angularSizeArcmin = 28.0,
            surfaceBrightness = 13.0,
            description = "Famosa nebulosa tripartida dividida por faixas de poeira escura, combinando emissão e reflexão.",
            bestFilter = "UHC"
        ),
        DeepSkyObject(
            id = "M4",
            messierNgc = "M4 / NGC 6121",
            commonName = "Aglomerado Globular de Escorpião",
            constellation = "Escorpião",
            type = DeepSkyType.GLOBULAR_CLUSTER,
            rightAscensionHours = 16.393,
            declinationDeg = -26.53,
            apparentMagnitude = 5.9,
            angularSizeArcmin = 36.0,
            surfaceBrightness = 12.8,
            description = "Um dos aglomerados globulares mais próximos da Terra, localizado muito próximo da estrela Antares.",
            bestFilter = "Nenhum"
        ),
        DeepSkyObject(
            id = "M22",
            messierNgc = "M22 / NGC 6656",
            commonName = "Grande Aglomerado de Sagitário",
            constellation = "Sagitário",
            type = DeepSkyType.GLOBULAR_CLUSTER,
            rightAscensionHours = 18.608,
            declinationDeg = -23.90,
            apparentMagnitude = 5.1,
            angularSizeArcmin = 32.0,
            surfaceBrightness = 12.1,
            description = "Aglomerado globular espetacular do hemisfério sul, excepcionalmente rico e fácil de resolver em estrelas.",
            bestFilter = "Nenhum"
        ),
        DeepSkyObject(
            id = "M7",
            messierNgc = "M7 / NGC 6475",
            commonName = "Aglomerado de Ptolomeu",
            constellation = "Escorpião",
            type = DeepSkyType.OPEN_CLUSTER,
            rightAscensionHours = 17.898,
            declinationDeg = -34.82,
            apparentMagnitude = 3.3,
            angularSizeArcmin = 80.0,
            surfaceBrightness = 11.8,
            description = "Brilhante e vasto aglomerado aberto conhecido desde a Antiguidade por Ptolomeu.",
            bestFilter = "Nenhum"
        ),
        DeepSkyObject(
            id = "M6",
            messierNgc = "M6 / NGC 6405",
            commonName = "Aglomerado da Borboleta",
            constellation = "Escorpião",
            type = DeepSkyType.OPEN_CLUSTER,
            rightAscensionHours = 17.668,
            declinationDeg = -32.22,
            apparentMagnitude = 4.2,
            angularSizeArcmin = 25.0,
            surfaceBrightness = 11.2,
            description = "Aglomerado aberto cujo arranjo estelar lembra o formato das asas abertas de uma borboleta.",
            bestFilter = "Nenhum"
        ),
        DeepSkyObject(
            id = "NGC4755",
            messierNgc = "NGC 4755",
            commonName = "Caixa de Joias (Jewel Box)",
            constellation = "Cruzeiro do Sul",
            type = DeepSkyType.OPEN_CLUSTER,
            rightAscensionHours = 12.893,
            declinationDeg = -60.33,
            apparentMagnitude = 4.2,
            angularSizeArcmin = 10.0,
            surfaceBrightness = 9.5,
            description = "Um dos aglomerados mais deslumbrantes do hemisfério sul, apresentando estrelas de cores contrastantes (azuis e uma gigante vermelha central).",
            bestFilter = "Nenhum"
        ),
        DeepSkyObject(
            id = "NGC5139",
            messierNgc = "NGC 5139",
            commonName = "Ômega Centauri",
            constellation = "Centauro",
            type = DeepSkyType.GLOBULAR_CLUSTER,
            rightAscensionHours = 13.447,
            declinationDeg = -47.48,
            apparentMagnitude = 3.9,
            angularSizeArcmin = 36.0,
            surfaceBrightness = 11.0,
            description = "O maior e mais massivo aglomerado globular da Via Láctea, contendo milhões de estrelas. Uma joia do céu austral.",
            bestFilter = "Nenhum"
        ),
        DeepSkyObject(
            id = "M16",
            messierNgc = "M16 / NGC 6611",
            commonName = "Nebulosa da Águia (Pilares da Criação)",
            constellation = "Serpente",
            type = DeepSkyType.NEBULA,
            rightAscensionHours = 18.313,
            declinationDeg = -13.79,
            apparentMagnitude = 6.0,
            angularSizeArcmin = 35.0,
            surfaceBrightness = 13.0,
            description = "Aglomerado jovem envolvido por nebulosidade de emissão contendo os famosos Pilares da Criação.",
            bestFilter = "UHC ou OIII"
        ),
        DeepSkyObject(
            id = "M17",
            messierNgc = "M17 / NGC 6618",
            commonName = "Nebulosa Ômega (ou do Cisne)",
            constellation = "Sagitário",
            type = DeepSkyType.NEBULA,
            rightAscensionHours = 18.347,
            declinationDeg = -16.18,
            apparentMagnitude = 6.0,
            angularSizeArcmin = 11.0,
            surfaceBrightness = 11.0,
            description = "Nebulosa de emissão brilhante com contorno característico lembrando um cisne nadando ou a letra grega Ômega.",
            bestFilter = "UHC ou OIII"
        ),
        DeepSkyObject(
            id = "M11",
            messierNgc = "M11 / NGC 6705",
            commonName = "Aglomerado do Pato Selvagem",
            constellation = "Escudo",
            type = DeepSkyType.OPEN_CLUSTER,
            rightAscensionHours = 18.852,
            declinationDeg = -6.27,
            apparentMagnitude = 5.8,
            angularSizeArcmin = 14.0,
            surfaceBrightness = 11.0,
            description = "Um dos aglomerados abertos mais densos e ricos conhecidos, lembrando quase um aglomerado globular fraco.",
            bestFilter = "Nenhum"
        ),
        DeepSkyObject(
            id = "ALBIREO",
            messierNgc = "Beta Cygni / Albireo",
            commonName = "Albireo",
            constellation = "Cisne",
            type = DeepSkyType.DOUBLE_STAR,
            rightAscensionHours = 19.512,
            declinationDeg = 27.96,
            apparentMagnitude = 3.1,
            angularSizeArcmin = 0.5,
            separationArcsec = 34.3,
            description = "A estrela dupla de cores contrastantes mais bela do céu: uma primária dourada/alaranjada e uma companheira azul-safira.",
            bestFilter = "Nenhum"
        ),
        DeepSkyObject(
            id = "M51",
            messierNgc = "M51 / NGC 5194",
            commonName = "Galáxia do Redemoinho (Whirlpool)",
            constellation = "Cães de Caça",
            type = DeepSkyType.GALAXY,
            rightAscensionHours = 13.498,
            declinationDeg = 47.20,
            apparentMagnitude = 8.4,
            angularSizeArcmin = 11.0,
            surfaceBrightness = 13.2,
            description = "Galáxia espiral vista de frente interagindo diretamente com a companheira menor NGC 5195.",
            bestFilter = "Nenhum"
        ),
        DeepSkyObject(
            id = "M104",
            messierNgc = "M104 / NGC 4594",
            commonName = "Galáxia do Sombrero",
            constellation = "Virgem",
            type = DeepSkyType.GALAXY,
            rightAscensionHours = 12.666,
            declinationDeg = -11.62,
            apparentMagnitude = 8.0,
            angularSizeArcmin = 9.0,
            surfaceBrightness = 11.8,
            description = "Galáxia espiral com bojo brilhante e proeminente faixa de poeira escura no equador, lembrando um chapéu sombrero.",
            bestFilter = "Nenhum"
        ),
        DeepSkyObject(
            id = "NGC253",
            messierNgc = "NGC 253",
            commonName = "Galáxia do Escultor",
            constellation = "Escultor",
            type = DeepSkyType.GALAXY,
            rightAscensionHours = 0.792,
            declinationDeg = -25.29,
            apparentMagnitude = 7.2,
            angularSizeArcmin = 27.5,
            surfaceBrightness = 12.8,
            description = "Galáxia espiral intermediária brilhante no céu austral, muito rica em estruturas e filamentos de poeira.",
            bestFilter = "Nenhum"
        ),
        DeepSkyObject(
            id = "M1",
            messierNgc = "M1 / NGC 1952",
            commonName = "Nebulosa do Caranguejo",
            constellation = "Touro",
            type = DeepSkyType.NEBULA,
            rightAscensionHours = 5.575,
            declinationDeg = 22.01,
            apparentMagnitude = 8.4,
            angularSizeArcmin = 6.0,
            surfaceBrightness = 12.0,
            description = "Remanescente da famosa supernova observada por astrônomos chineses no ano 1054 d.C.",
            bestFilter = "UHC ou OIII"
        )
    )

    fun findById(id: String): DeepSkyObject? = objects.firstOrNull { it.id.equals(id, ignoreCase = true) }
}
