name: Build Android AAB

on:
  push:
    branches: [ "main", "master", "principal" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.7'

      - name: Locate and Build AAB
        run: |
          TARGET_DIR=$(find . -name "build.gradle*" -exec dirname {} \; | tail -n 1)
          echo "Entrando na pasta do projeto: $TARGET_DIR"
          cd "$TARGET_DIR"
          gradle bundleRelease
          
      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: '**/*.aab'
